/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Frame;
import java.awt.event.ActionListener;
import java.util.Map;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;

/**
 *
 * @author Iperez
 */
public class BibliotecaGUI extends javax.swing.JFrame {

    /**
     * Creates new form BibliotecaGUI
     */
    public BibliotecaGUI() throws ClassNotFoundException {
        try{
            for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels())
              {
               if ("Nimbus".equals(info.getName()))
                   {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                   }
               }
        } catch (Exception e){e.printStackTrace();}
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtbMenu = new javax.swing.JToolBar();
        btnLibros = new javax.swing.JButton();
        btnPrestamos = new javax.swing.JButton();
        btnSocios = new javax.swing.JButton();
        jdpPrincipal = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtbMenu.setBackground(java.awt.Color.lightGray);
        jtbMenu.setFloatable(false);
        jtbMenu.setForeground(new java.awt.Color(240, 240, 240));
        jtbMenu.setRollover(true);
        jtbMenu.setAlignmentX(0.0F);

        btnLibros.setText("Libros");
        btnLibros.setFocusable(false);
        btnLibros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLibros.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbMenu.add(btnLibros);

        btnPrestamos.setText("Prestamos");
        btnPrestamos.setFocusable(false);
        btnPrestamos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPrestamos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbMenu.add(btnPrestamos);

        btnSocios.setText("Socios");
        btnSocios.setFocusable(false);
        btnSocios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSocios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jtbMenu.add(btnSocios);

        getContentPane().add(jtbMenu, java.awt.BorderLayout.NORTH);

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 542, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 545, Short.MAX_VALUE)
        );

        getContentPane().add(jdpPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setListener(ActionListener accion) {
        this.btnSocios.addActionListener(accion);
        this.btnLibros.addActionListener(accion);
        this.btnPrestamos.addActionListener(accion);
    }
    
    public void setComandos(Map<String,String> comando){
        //Control de errores
        try{
            this.btnSocios.setActionCommand(comando.get("SOCIOS"));
            this.btnLibros.setActionCommand(comando.get("LIBROS"));
            this.btnPrestamos.setActionCommand(comando.get("PRESTAMOS"));
        }catch (NullPointerException e) {
           System.out.println("Error de NullPointer Exception");
        }catch(ClassCastException e){
            System.out.println("Error de ClassCast Exception");
        }catch(Exception e){
            System.out.println("Otro Error");
      
        }
    }

    public JDesktopPane getJdpPrincipal() {
        return jdpPrincipal;
    }

    public void setJdpPrincipal(JDesktopPane jdpPrincipal) {
        this.jdpPrincipal = jdpPrincipal;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLibros;
    private javax.swing.JButton btnPrestamos;
    private javax.swing.JButton btnSocios;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JToolBar jtbMenu;
    // End of variables declaration//GEN-END:variables
}
